#+TITLE: Brewing temperature controler
#+AUTHOR:
#+OPTIONS: toc:nil
#+OPTIONS: ^:nil
#+OPTIONS: H:4
#+OPTIONS: num:nil
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,12pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Temperature sensor DS18B20
The DS18B20 temperature sensor is used in a sealed version. The fact that the sensor is placed inside a sealed container increases the temperature response time.
The step response of the temperature sensor has been measured and the corresponding first order system has been identified :
\begin{equation}
s_s(t) = 1 - e^{-\frac{t}{11.3568}}.
\end{equation}
This means that more than 33s is necesssary for the sensor to recover 99\% of the final temperature. This sensor is only suited to measure very slow processes, such has a room temperature for example.
It is necessary to acount for this slow transfer function from real to measured temperature in order to improve the contoler abilities.\\
The corresponding indicail response is :
\begin{equation}
s_i(t) = H(t) e^{-\frac{t}{11.3568}},
\end{equation}
where H(t) is the Heaviside function. The measured temperature $T_m$ is obtained from the real
temperature $T$ via the following convultion :
\begin{eqnarray}
T_m(t) &= &\int_{-\infty}^{+\infty} T(\tau) s_i(t-\tau) d \tau\\
\end{eqnarray}
